# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32, verbose_name='Nombre')),
                ('code_color', models.TextField(max_length=32, verbose_name='Código color')),
            ],
            options={
                'verbose_name': 'Color',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=32, null=True, verbose_name='Nombre')),
                ('type_animal', models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato'), ('bird', 'Pájaro'), ('reptile', 'Reptil'), ('other', 'Otro')], default='', max_length=32, verbose_name='Tipo')),
                ('breed', models.TextField(blank=True, null=True, verbose_name='Raza')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pets', verbose_name='Foto')),
                ('location', models.CharField(default='', max_length=50, verbose_name='Ubicacion')),
                ('color', models.ManyToManyField(to='core.Color')),
            ],
            options={
                'verbose_name': 'Mascota',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Pet')),
            ],
            options={
                'verbose_name': 'Publicación',
            },
        ),
    ]
