# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32, verbose_name='Nombre')),
                ('code_color', models.TextField(max_length=32, verbose_name='Código color')),
            ],
            options={
                'verbose_name': 'Color',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nombre')),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Número de teléfono')),
                ('city', models.TextField(blank=True, max_length=20, null=True, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Socio',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=32, null=True, verbose_name='Nombre')),
                ('type_animal', models.CharField(choices=[('dog', 'perro'), ('gato', 'Gato'), ('bird', 'Pájaro'), ('reptil', 'Reptil'), ('other', 'Otro')], default='', max_length=32, verbose_name='Tipo')),
                ('breed', models.TextField(blank=True, null=True, verbose_name='Raza')),
                ('number_color', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', verbose_name='Número de colores')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('color', models.ManyToManyField(to='core.Color')),
            ],
            options={
                'verbose_name': 'Mascota',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('location', models.TextField(default='', max_length=100, verbose_name='Localización')),
                ('pet', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='core.Pet')),
            ],
            options={
                'verbose_name': 'Publicación',
            },
        ),
    ]
