# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de teléfono'),
        ),
    ]
