# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='state_publication',
            field=models.CharField(choices=[('found', 'Buscando al propietario'), ('lost', 'Buscando mi mascota'), ('solved', 'Solucionado')], default='', max_length=32, verbose_name='Estado'),
        ),
    ]
