# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.ManyToManyField(to='core.Color'),
        ),
        migrations.AddField(
            model_name='publication',
            name='location',
            field=models.TextField(default='', max_length=100, verbose_name='Localización'),
        ),
        migrations.AddField(
            model_name='publication',
            name='pet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='core.Pet'),
        ),
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.TextField(blank=True, null=True, verbose_name='Raza'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.TextField(blank=True, max_length=32, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='number_color',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=32, verbose_name='Número de colores'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type_animal',
            field=models.CharField(choices=[('dog', 'perro'), ('gato', 'Gato'), ('bird', 'Pájaro'), ('reptil', 'Reptil'), ('other', 'Otro')], default='', max_length=32, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.TextField(default='', max_length=100, verbose_name='Título'),
        ),
    ]
