# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170607_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pets', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type_animal',
            field=models.CharField(choices=[('dog', 'Perro'), ('gato', 'Gato'), ('bird', 'Pájaro'), ('reptil', 'Reptil'), ('other', 'Otro')], default='', max_length=32, verbose_name='Tipo'),
        ),
    ]
