# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170609_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type_animal',
            field=models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato'), ('bird', 'Pájaro'), ('reptile', 'Reptil'), ('other', 'Otro')], default='', max_length=32, verbose_name='Tipo'),
        ),
    ]
